---
title: "quartose"
vignette: >
  %\VignetteIndexEntry{quartose}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
#| label: packages
#| message: false
library(knitr)
library(dplyr)
library(purrr)
library(ggplot2)
```

## Tabs and sections

### Printing in a loop

```{r}
#| label: tabs-and-headers
#| results: asis
for(sp in c("Adelie", "Chinstrap")) {
  dat <- penguins |> filter(species == sp)
  pic <- ggplot(dat, aes(bill_len, bill_dep, color = sex)) + geom_point()
  knit_print(quarto_tabset(
    content = list("Plot" = pic, "Data" = dat), 
    title = sp,
    level = 4
  ))
}
```

### Printing as a group

```{r}
#| label: tabs-and-headers-2
#| results: asis
isl <- c("Torgersen", "Biscoe", "Dream")
dat <- map(isl, \(ii) filter(penguins, island == ii))
pic <- map(dat, \(dd) ggplot(dd, aes(bill_len, bill_dep, color = species)) + geom_point())
quarto_group(list(
  quarto_tabset(content = pic, names = isl, title = "Plot", level = 4),
  quarto_tabset(content = dat, names = isl, title = "Data", level = 4)
))
```

## Divs and spans

```{r}
#| label: div-1
#| results: asis
quarto_div(
  content = "This is some margin text.", 
  class = "column-margin"
)
```


```{r}
#| label: div-2
#| results: asis
quarto_div(
  content = c(
    "Using character vectors is fine.",
    "This is also just one margin text block.", 
    "All the strings get pasted together,",
    "with a separator."
  ),
  class = "column-margin",
  sep = " /// "
)
```


```{r}
#| label: div-3
#| results: asis
quarto_div(
  content = list(
    "You can pass a list as the div content.", 
    "That allows you to mix content,",
    1:3,
    c("of different types", "and lengths."),
    "But pay attention to where separators appear,",
    "and remember that **markdown parsing still applies**"
  ),
  class = "column-margin",
  sep = " /// "
)
```


```{r}
#| label: div-4
#| results: asis
quarto_div(
  content = "This is a callout note.",
  class = "callout-note"
)

```


```{r}
#| label: div-5
#| results: asis
quarto_div(
  content = "You can supply multiple classes",
  class = c("column-margin", "callout-tip")
)
```


```{r}
#| label: span-1
#| results: asis
quarto_span(content = "this is highlighted", class = "mark")
```

```{r}
#| label: span-2
#| results: asis
quarto_div(
  content = list(
    quarto_span(content = "this is plain text"),
    quarto_span(content = "this is highlighted", class = "mark"),
    quarto_span(content = "this is underlined", class = "underline")
  ),
  sep = ", "
)
```

## Raw markdown

```{r}
#| label: raw-1
#| results: asis
quarto_markdown(
  content = c(
    "- this ends up being",
    "- a markdown list", 
    "- with **formatting**"
  ),
  sep = "\n"
)
```

